services:
  mongodb:
    image: mongo:7.0.23
    container_name: mrern-open-library-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
    volumes:
      - ./data/mongodb:/data/db
  redis:
    image: redis/redis-stack:latest
    container_name: mrern-open-library-redis
    restart: always
    environment:
      - REDIS_ARGS="--requirepass ${REDIS_PASS}"
    volumes:
      - ./data/redis:/data
    depends_on:
      - mongodb
  mailpit:
    image: axllent/mailpit:latest
    container_name: mrern-open-library-mailpit
    restart: always
  server:
    build: ./server
    image: virezee/mrern-open-library-express:latest
    container_name: mrern-open-library-express
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - mongodb
      - redis
      - mailpit
  client:
    build: ./client
    image: virezee/mrern-open-library-react:latest
    container_name: mrern-open-library-react
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
      - mailpit
      - server